/*
Authorship:Rida Allah Jaija,
Purpose:A little comparison between three mining devices to determine the most efficient based on their attributes.
date: september 13, 2022
*/
#include<stdio.h>
#include<string.h>
struct Miner{
    char made_by[20];
    char model[10];
    char algorythm[10];
    char hashrate_unit[10];
    char release_date[20];
    float maximum_hashrate;
    int power_consumption;
    int noise_db;
    float profit_perDay;
};
int main(){
    int num;
    printf("please enter the number of minning rigs you have: ");
    scanf("%d", &num);


    struct Miner KD6;
    strcpy(KD6.model,"kd6");
    strcpy(KD6.made_by,"Goldshell");
    strcpy(KD6.algorythm,"kadena");
    strcpy(KD6.hashrate_unit,"Th/s");
    strcpy(KD6.release_date,"April 2022");
    KD6.maximum_hashrate=26.3;
    KD6.power_consumption=2630;
    KD6.noise_db=80;
    KD6.profit_perDay=187.6;


    struct Miner CK6;
    strcpy(CK6.model,"ck6");
    strcpy(CK6.made_by,"Goldshell");
    strcpy(CK6.algorythm,"Eaglesong");
    strcpy(CK6.hashrate_unit,"Th/s");
    strcpy(CK6.release_date,"December 2021");
    CK6.maximum_hashrate=19.3;
    CK6.power_consumption=3300;
    CK6.noise_db=80;
    CK6.profit_perDay=26.42;


    struct Miner AntminerL7;
    strcpy(AntminerL7.model,"AntminerL7");
    strcpy(AntminerL7.made_by,"Bitmain");
    strcpy(AntminerL7.algorythm,"Scrypt");
    strcpy(AntminerL7.hashrate_unit,"GH/s");
    strcpy(AntminerL7.release_date,"November 2021");
    AntminerL7.maximum_hashrate=9.5;
    AntminerL7.power_consumption=3425;
    AntminerL7.noise_db=75;
    AntminerL7.profit_perDay=62.76;


    printf("\n%s: ",KD6.model);
    printf("\n  energie consumed by using %d minnig rigs is : %d",num,(KD6.power_consumption*num));
    printf("\n  profit generated by using %d minnig rigs is : %.2f",num,(KD6.profit_perDay*num));
    printf("\n%s: ",CK6.model);
    printf("\n  energie consumed by using %d minnig rigs is : %d",num,(CK6.power_consumption*num));
    printf("\n  profit generated by using %d minnig rigs is : %.2f",num,(CK6.profit_perDay*num));
    printf("\n%s: ",AntminerL7.model);
    printf("\n  energie consumed by using %d minnig rigs is : %d",num,(AntminerL7.power_consumption*num));
    printf("\n  profit generated by using %d minnig rigs is : %.2f",num,(AntminerL7.profit_perDay*num));
    return 0;
}